### ISSUE TITLE
not sure about this

### ISSUE THREAD

**Issue by uDAREGriev** [VanillaPlusPlus/VPPSpawnSelection#2]
20:46:02 SCRIPT    (W): @"VPPSpawnSelection/4_World/plugins\pluginbase\spawnselector\spawnselector.c,68": Missing ';' at the end of line

**Comment by GravityWolfNotAmused** [comment]
Does it cause a crash?

**Comment by GravityWolfNotAmused** [comment]
but, regardless: https://github.com/VanillaPlusPlus/VPPSpawnSelection/commit/39b4760b837ec37d1c7d8e4cde506d3d6cea6d8e
