### ISSUE TITLE
spawn selection broken

### ISSUE THREAD

**Issue by imonpcp** [VanillaPlusPlus/VPPSpawnSelection#4]
playing dayZ sa on the usonia#1 server. every person I play with including myself are experiencing spawn issues. when selecting certain spawns, it does not spawn you in the correct locations. so far cherno and balota 100% are fine. basically half of the selections are not spawning to the correct location.

**Comment by imonpcp** [comment]
cherno 1 or cherno 2 spawns you in the far NE by the ship
kamenka  spawns to the east of electro.

**Comment by GravityWolfNotAmused** [comment]
how often do you use those spawns?

**Comment by imonpcp** [comment]
I try different spawns daily to every other day depending if I die. I pvp alot do daily death occurs alot
________________________________

**Comment by GravityWolfNotAmused** [comment]
So, what I believe is happening is that you are choosing a spawn point, and then choosing the same spawn point before the cooldown is completed, and requesting the same point which is giving you a random spawn point that is not the one you picked.

When we are finished with recreating the admin tools, I will lock the button for when you select a spawn point that is on cool down.

**Comment by imonpcp** [comment]
Incorrect. Ive been paying attention to the cooldowns and not selecting red spawns. However that may be a glitch where the tool believes its in cooldown and random spawning.it is happening regardless of amount of deaths 0-100 certain spawns are not spawning in the correct location.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by GravityWolfNotAmused** [comment]
I don't set any sort of offset to any of the spawn points, so they are as Shu configured them to be. I can look into the Cooldown function, and see if it causes issues.

**Comment by imonpcp** [comment]
Sure, anything lol. I have no knowledge of the configurations. I can only state the problem as users are experiencing, and as I experience them.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
